version: "3"

x-base-app-conf: &base_app_conf
    env_file: .env
    stdin_open: true
    tty: true

services:
    myproject:
        <<: *base_app_conf
        image: myproject:latest
        container_name: myproject
        restart: always
        build:
            context: .
            dockerfile: docker/Dockerfile
        depends_on:
            - db

    db:
        image: postgres:16.0-alpine
        container_name: db
        restart: always
        environment:
            - POSTGRES_DB=mydatabase
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
