version: "3"

x-base-app-conf: &base_app_conf
    env_file: .env
    stdin_open: true
    tty: true

services:
    myproject:
        <<: *base_app_conf
        image: myproject:latest
        container_name: myproject
        restart: always
        build:
            context: .
            dockerfile: docker/Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - "./app:/src/app"
        depends_on:
            - db
            - django-migrations

    # Apply Django migrations
    django-migrations:
        <<: *base_app_conf
        image: myproject:latest
        container_name: django-migrations
        command: python manage.py migrate
        restart: no
        build:
            context: .
            dockerfile: docker/Dockerfile
        volumes:
            - "./app:/src/app"
        depends_on:
            - db

    webpack-watch:
        <<: *base_app_conf
        image: myproject:latest
        container_name: webpack-watch
        working_dir: /src
        command: npm run dev
        restart: always
        volumes:
            - "./app:/src/app"
        depends_on:
            - myproject

    db:
        image: postgres:16.0-alpine
        command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
        container_name: db
        restart: always
        environment:
            - POSTGRES_DB=mydatabase
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
        volumes:
            - db:/var/lib/postgresql/data
volumes:
    db:
