version: 2.1

# orbs:

#######################################
## ANCHORS
#######################################

# build-and-push-image: &build-and-push-image
# deploy_ecs: &deploy_ecs

#######################################
## EXECUTORS
#######################################
executors:
  default:
    working_directory: ~/repo
    docker:
      - image: cimg/base:2023.09
        environment:
          DJANGO_SETTINGS_MODULE: myproject.settings.development
          SECRET_KEY: secret
          DEBUG: True
          DB_NAME: mydatabase
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_HOST: db
          DB_PORT: 5432

#######################################
## JOBS
#######################################
jobs:
  checkout_code:
    executor: default
    resource_class: small
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  docker_run_tests:
    executor: default
    working_directory: ~/repo
    resource_class: medium
    steps:
      - attach_workspace:
          at: ~/repo
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: run tests and run coverage
          command: |
            env > .env
            make circleci-up
            make circleci-tests
            mkdir test-results && docker cp $(docker ps -qf "name=myproject"):/src/test-results/junit.xml ./test-results/junit.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

#######################################
## WORKFLOWS
#######################################
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - docker_run_tests:
          requires:
            - checkout_code
